version: '3.4'
name: "Net Service"

services:
  catalogdb:
    image: mongo
  
  basketdb:
    image: redis
  
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  basket.api:
    image: basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes: 
  mongo_data: